# This is the network config written by 'subiquity'
network:
  ethernets:
    ens33:
      dhcp4: no
      optional: true
      addresses: [192.168.131.131/24]
        #gateway4: 192.168.131.1
      nameservers:
              addresses: [114.114.114.114,8.8.8.8]
      routes:
              - to: 0.0.0.0/0
                via: 192.168.131.1
                metric: 90

      dhcp6: no
    ens34:
      dhcp4: no
      addresses: [192.168.132.131/24]
        #gateway4: 192.168.132.1
        #routes:
        #        - to: 0.0.0.0/0
        #          via: 192.168.132.1
        #          metric: 120
      dhcp6: no
    ens38:
      dhcp4: yes
      optional: true
      dhcp4-overrides:
                route-metric: 1100
      dhcp6: yes
      dhcp6-overrides:
                route-metric: 1100
  version: 2
